dist: bionic
sudo: required

language: java
jdk:
  - openjdk11

notifications:
  email: acogoluegnes@vmware.io
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:22.3.4.1-1
branches:
  only:
    - master
    - 1.4.x

before_script:
  - ./bin/before_build.sh
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: ./gradlew check -i -s -Drabbitmqctl.bin="rabbitmq/sbin/rabbitmqctl -n rabbit@$(hostname)"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
